version: "3"

services:
  nest:
    build: .
    environment:
    - API_PORT
    ports:
    - $API_PORT:$API_PORT
    networks:
    - docker-nest-typegoose-net
    depends_on:
    - mongo
  mongo:
    image: mongo:4.2
    expose:
    - 27017
    networks:
    - docker-nest-typegoose-net

networks:
  docker-nest-typegoose-net:
    driver: bridge
